brew "fzf"
brew "git"
brew "neovim"
brew "zig"
brew "zls"
brew "zsh"
cask "1password", args: { appdir: "/Applications" }
cask "font-martian-mono-nerd-font"
cask "ghostty"
cask "obsidian"
cask "spotify"
